### Урок 4. ДЗ Часть 1 ###

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

In [1]:
import numpy as np
import fractions

In [2]:
A = np.array([[1, 1, -1, -2],
             [2, 1, -1, 1],
             [1, 1, -3, 1]])
B = np.array([[0], [-2], [4]])

In [3]:
A_ = np.append(A, B, axis=1)
A_

array([[ 1,  1, -1, -2,  0],
       [ 2,  1, -1,  1, -2],
       [ 1,  1, -3,  1,  4]])

In [4]:
A_[1] = A_[1] + A_[0]*(-2)
A_

array([[ 1,  1, -1, -2,  0],
       [ 0, -1,  1,  5, -2],
       [ 1,  1, -3,  1,  4]])

In [5]:
A_[2] = A_[2] + A_[0]*(-1)
A_

array([[ 1,  1, -1, -2,  0],
       [ 0, -1,  1,  5, -2],
       [ 0,  0, -2,  3,  4]])

Система имеет бесконечное количество решений 
$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
-x_{2}+x_{3}+5x_{4}=-2, \\
-2x_{3}+3x_{4}=4.
\end{cases}$$

Допустим, что $x_{4}=c$, то 
$$
-2x_{3} = 4-3c \Leftrightarrow x_{3} =\frac{3}{2}c - 2 ,\\
x_{2} = 2 + \frac{3}{2}c - 2 + 5c \Leftrightarrow x_{2} = \frac{3}{2}c + 5c\\
x_{1} = -\frac{3}{2}c - 5c + \frac{3}{2}c - 2 + 2c \Leftrightarrow x_{1} = -2 - 3c
$$

При $c=0$ получим
$$ 
x_{1} = -2\\
x_{2} = 0\\
x_{3} = -2\\
x_{4} = 0
$$
Проверка
$$
\begin{cases}
-2 + 0 + 2 -0 = 0\\
-4 + 0 + 2 + 0 = -2\\
-2 + 0 + 6 + 0 = 4
\end{cases}
$$

<hr>

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

In [6]:
np.set_printoptions(formatter={'all':lambda x: str(fractions.Fraction(x).limit_denominator())})

In [7]:
# a

n = 3 # количество переменных
A  = np.array([[3, -1, 1],
               [2, -5, -3],
               [1, 1, -1]], float)
B = np.array([[4], [-17], [0]])

A_ = np.append(A, B, axis=1)
A_

array([[3, -1, 1, 4],
       [2, -5, -3, -17],
       [1, 1, -1, 0]])

In [8]:
A_[0] = A_[0]/3
A_

array([[1, -1/3, 1/3, 4/3],
       [2, -5, -3, -17],
       [1, 1, -1, 0]])

In [9]:
A_[1] = A_[1] - A_[0] * 2
A_

array([[1, -1/3, 1/3, 4/3],
       [0, -13/3, -11/3, -59/3],
       [1, 1, -1, 0]])

In [10]:
A_[2] = A_[2] - A_[0]
A_

array([[1, -1/3, 1/3, 4/3],
       [0, -13/3, -11/3, -59/3],
       [0, 4/3, -4/3, -4/3]])

In [11]:
A_[1] = A_[1] * -(3/13)
A_

array([[1, -1/3, 1/3, 4/3],
       [0, 1, 11/13, 59/13],
       [0, 4/3, -4/3, -4/3]])

In [12]:
A_[2] = A_[2] - A_[1]*(4/3)
A_

array([[1, -1/3, 1/3, 4/3],
       [0, 1, 11/13, 59/13],
       [0, 0, -32/13, -96/13]])

In [13]:
A_[2] = A_[2] * -(13/32)
A_

array([[1, -1/3, 1/3, 4/3],
       [0, 1, 11/13, 59/13],
       [0, 0, 1, 3]])

In [14]:
np.linalg.matrix_rank(A), np.linalg.matrix_rank(A_), n

(3, 3, 3)

$rang(A) = rang(A|B) = n$ -> система уравнений совместная и определена

In [15]:
# б

n = 3 # количество переменных
A  = np.array([[2, -4, 6],
               [1, -2, 3],
               [3, -6, 9]], float)
B = np.array([[1], [-2], [5]])

A_ = np.append(A, B, axis=1)
A_

array([[2, -4, 6, 1],
       [1, -2, 3, -2],
       [3, -6, 9, 5]])

In [16]:
A_[1] = A_[1] - A_[0]*.5
A_

array([[2, -4, 6, 1],
       [0, 0, 0, -5/2],
       [3, -6, 9, 5]])

In [17]:
A_[2] = A_[0]*A_[1]
A_

array([[2, -4, 6, 1],
       [0, 0, 0, -5/2],
       [0, 0, 0, -5/2]])

In [18]:
A_[2] = A_[1] - A_[1]
A_

array([[2, -4, 6, 1],
       [0, 0, 0, -5/2],
       [0, 0, 0, 0]])

In [19]:
np.linalg.matrix_rank(A), np.linalg.matrix_rank(A_), n

(1, 2, 3)

$rang(A) \neq rang(A|B) \neq n$ -> система уравнений несовместная

In [20]:
# в

n = 3 # количество переменных
A  = np.array([[1, 2, 5],
               [3, 1, -8]], float)
B = np.array([[4], [-2]])

A_ = np.append(A, B, axis=1)
A_

array([[1, 2, 5, 4],
       [3, 1, -8, -2]])

In [21]:
A_[1] = A_[1] - A_[0]*3
A_

array([[1, 2, 5, 4],
       [0, -5, -23, -14]])

In [22]:
np.linalg.matrix_rank(A), np.linalg.matrix_rank(A_), n

(2, 2, 3)

$rang(A) = rang(A|B) < n$ -> система уравнений совместная, но не определена

<hr>

__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

In [23]:
n = 4 # количество переменных
A  = np.array([[1, 3, -2, 4],
               [0, 5, 0, -1],
               [0, 0, 3, 0],
               [0, 0, 0, 2]], float)
B = np.array([[3], [2], [4], [1]])

A_ = np.append(A, B, axis=1)
A_

array([[1, 3, -2, 4, 3],
       [0, 5, 0, -1, 2],
       [0, 0, 3, 0, 4],
       [0, 0, 0, 2, 1]])

In [24]:
np.linalg.matrix_rank(A), np.linalg.matrix_rank(A_), n

(4, 4, 4)

Система совместна и определена -> имеет одно решение

<hr>

__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

In [25]:
import sympy as sp

In [26]:
n = 3 # количество переменных

a, b, c = sp.symbols('a b c')

A  = sp.Matrix([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
B = sp.Matrix([[a], [b], [c]])

A_ = A.col_insert(3, B)
A_

Matrix([
[1, 2, 3, a],
[4, 5, 6, b],
[7, 8, 9, c]])

In [27]:
A_[1,:] = A_[0,:] * 4 - A_[1,:]
A_

Matrix([
[1, 2, 3,       a],
[0, 3, 6, 4*a - b],
[7, 8, 9,       c]])

In [28]:
A_[2,:] = A_[2,:] - A_[0,:] * 7
A_

Matrix([
[1,  2,   3,        a],
[0,  3,   6,  4*a - b],
[0, -6, -12, -7*a + c]])

In [29]:
A_[2,:] = A_[2,:] + A_[1,:] * 2
A_

Matrix([
[1, 2, 3,           a],
[0, 3, 6,     4*a - b],
[0, 0, 0, a - 2*b + c]])

In [30]:
A.rank(), A_.rank(), n

(2, 3, 3)

При $ (a - 2b + c) \neq 0 $ система будет несовместной

### Часть 2 ###

<hr>

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

In [31]:
# a

A = np.array([[1, -2],
               [3, -4]])
B = np.array([[1], [7]])
A

array([[1, -2],
       [3, -4]])

In [32]:
det = np.linalg.det(A)
det

2.0000000000000004

In [33]:
A_1 = A.copy()
A_1[:, 0] = B[:, 0]
A_1

array([[1, -2],
       [7, -4]])

In [34]:
det_1 = np.linalg.det(A_1)
det_1

9.999999999999998

In [35]:
A_2 = A.copy()
A_2[:, 1] = B[:, 0]
A_2

array([[1, 1],
       [3, 7]])

In [36]:
det_2 = np.linalg.det(A_2)
det_2

4.0

In [37]:
x1 = det_1 / det
x2 = det_2 / det
x1, x2

(4.999999999999998, 1.9999999999999996)

In [38]:
# б

A = np.array([[2, -1, 5],
              [1, 1, -3], 
              [2, 4, 1]])
B = np.array([[10], [-2], [1]])
A

array([[2, -1, 5],
       [1, 1, -3],
       [2, 4, 1]])

In [39]:
det = np.linalg.det(A)
det

42.99999999999998

In [40]:
A_1 = A.copy()
A_1[:, 0] = B[:, 0]

det_1 = np.linalg.det(A_1)
A_1, det_1

(array([[10, -1, 5],
        [-2, 1, -3],
        [1, 4, 1]]),
 86.00000000000004)

In [41]:
A_2 = A.copy()
A_2[:, 1] = B[:, 0]

det_2 = np.linalg.det(A_2)
A_2, det_2

(array([[2, 10, 5],
        [1, -2, -3],
        [2, 1, 1]]),
 -43.000000000000014)

In [42]:
A_3 = A.copy()
A_3[:, 2] = B[:, 0]

det_3 = np.linalg.det(A_3)
A_3, det_3

(array([[2, -1, 10],
        [1, 1, -2],
        [2, 4, 1]]),
 42.99999999999998)

In [43]:
x1 = det_1 / det
x2 = det_2 / det
x3 = det_3 / det
x1, x2, x3

(2.0000000000000018, -1.0000000000000009, 1.0)

<hr>

__2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    

In [44]:
# a

L = np.eye(3)

A = np.array([[1, 2, 4],
              [2, 9, 12], 
              [3, 26, 30]])
A

array([[1, 2, 4],
       [2, 9, 12],
       [3, 26, 30]])

In [45]:
A[1] = A[1] - A[0] * 2

L[1, 0] = 2
A, L

(array([[1, 2, 4],
        [0, 5, 4],
        [3, 26, 30]]),
 array([[1, 0, 0],
        [2, 1, 0],
        [0, 0, 1]]))

In [46]:
A[2] = A[2] - A[0] * 3

L[2, 0] = 3
A, L

(array([[1, 2, 4],
        [0, 5, 4],
        [0, 20, 18]]),
 array([[1, 0, 0],
        [2, 1, 0],
        [3, 0, 1]]))

In [47]:
A[2] = A[2] - A[1] * 4

L[2, 1] = 4
A, L

(array([[1, 2, 4],
        [0, 5, 4],
        [0, 0, 2]]),
 array([[1, 0, 0],
        [2, 1, 0],
        [3, 4, 1]]))

In [48]:
L @ A

array([[1, 2, 4],
       [2, 9, 12],
       [3, 26, 30]])

   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

In [49]:
# б

L = np.eye(4)

A = np.array([[1, 1, 2, 4],
              [2, 5, 8, 9], 
              [3, 18, 29, 18],
              [4, 22, 53, 33]])
A

array([[1, 1, 2, 4],
       [2, 5, 8, 9],
       [3, 18, 29, 18],
       [4, 22, 53, 33]])

In [50]:
A[1] = A[1] - A[0] * 2

L[1, 0] = 2
A, L

(array([[1, 1, 2, 4],
        [0, 3, 4, 1],
        [3, 18, 29, 18],
        [4, 22, 53, 33]]),
 array([[1, 0, 0, 0],
        [2, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]]))

In [51]:
A[2] = A[2] - A[0] * 3

L[2, 0] = 3
A, L

(array([[1, 1, 2, 4],
        [0, 3, 4, 1],
        [0, 15, 23, 6],
        [4, 22, 53, 33]]),
 array([[1, 0, 0, 0],
        [2, 1, 0, 0],
        [3, 0, 1, 0],
        [0, 0, 0, 1]]))

In [52]:
A[3] = A[3] - A[0] * 4

L[3, 0] = 4
A, L

(array([[1, 1, 2, 4],
        [0, 3, 4, 1],
        [0, 15, 23, 6],
        [0, 18, 45, 17]]),
 array([[1, 0, 0, 0],
        [2, 1, 0, 0],
        [3, 0, 1, 0],
        [4, 0, 0, 1]]))

In [53]:
A[2] = A[2] - A[1] * 5

L[2, 1] = 5
A, L

(array([[1, 1, 2, 4],
        [0, 3, 4, 1],
        [0, 0, 3, 1],
        [0, 18, 45, 17]]),
 array([[1, 0, 0, 0],
        [2, 1, 0, 0],
        [3, 5, 1, 0],
        [4, 0, 0, 1]]))

In [54]:
A[3] = A[3] - A[1] * 6

L[3, 1] = 6
A, L

(array([[1, 1, 2, 4],
        [0, 3, 4, 1],
        [0, 0, 3, 1],
        [0, 0, 21, 11]]),
 array([[1, 0, 0, 0],
        [2, 1, 0, 0],
        [3, 5, 1, 0],
        [4, 6, 0, 1]]))

In [55]:
A[3] = A[3] - A[2] * 7

L[3, 2] = 7
A, L

(array([[1, 1, 2, 4],
        [0, 3, 4, 1],
        [0, 0, 3, 1],
        [0, 0, 0, 4]]),
 array([[1, 0, 0, 0],
        [2, 1, 0, 0],
        [3, 5, 1, 0],
        [4, 6, 7, 1]]))

In [56]:
L @ A

array([[1, 1, 2, 4],
       [2, 5, 8, 9],
       [3, 18, 29, 18],
       [4, 22, 53, 33]])

<hr>

__3*.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

In [57]:
b = np.array([[1], [-6], [-5]])
U = np.array([[2, 1, 3],
              [11, 7, 5],
              [9, 8, 4]], float)
L = np.eye(3)

In [58]:
l = 11/2
U[1] = U[1] - U[0] * l

L[1, 0] = l
U, L

(array([[2, 1, 3],
        [0, 3/2, -23/2],
        [9, 8, 4]]),
 array([[1, 0, 0],
        [11/2, 1, 0],
        [0, 0, 1]]))

In [59]:
l = 9/2
U[2] = U[2] - U[0] * l

L[2, 0] = l
U, L

(array([[2, 1, 3],
        [0, 3/2, -23/2],
        [0, 7/2, -19/2]]),
 array([[1, 0, 0],
        [11/2, 1, 0],
        [9/2, 0, 1]]))

In [60]:
l = 7/3
U[2] = U[2] - U[1] * l

L[2, 1] = l
U, L

(array([[2, 1, 3],
        [0, 3/2, -23/2],
        [0, 0, 52/3]]),
 array([[1, 0, 0],
        [11/2, 1, 0],
        [9/2, 7/3, 1]]))

In [61]:
L @ U

array([[2, 1, 3],
       [11, 7, 5],
       [9, 8, 4]])

$$
Ly = b\\
\begin{cases}
y_{1}=1 \\
\frac{11}{2}y_{1} + y_{2}=-6 \\
\frac{9}{2}y_{1} + \frac{7}{3}y_{2} + y_{3}=-5
\end{cases}\\
y_{1} = 1, y_{2} = -\frac{23}{2}, y_{3} = \frac{52}{3}
$$


$$
Ux = y\\
\begin{cases}
2x_{1} + x_{2} + 3x_{3} = 1\\
\frac{3}{2}x_{2} - \frac{23}{2}x_{3} = -\frac{23}{2}\\
\frac{53}{3}x_{3} = \frac{53}{3}
\end{cases}\\
x_{3} = 1, x_{2} = 0, x_{1} = -1
$$

Проверка


$$\begin{cases}
-2 + 0 + 3 = 1\\
-11 + 0 + 5 = -6 \\
-9 + 0 + 4 = -5
\end{cases}$$

<hr>

__4*.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

In [62]:
A = np.array([[81, -45, 45],
              [-45, 50, -15],
              [45, -15, 38]])
A

array([[81, -45, 45],
       [-45, 50, -15],
       [45, -15, 38]])

In [63]:
L = np.zeros([3, 3])
L[0,0] = np.sqrt(A[0,0])
L[1,0] = A[1,0]/L[0,0]
L[2,0] = A[2,0]/L[0,0]

L[1,1] = np.sqrt(A[1,1] - L[1,0]**2)
L[2,1] = 1/L[1,1]*(A[2,1] - L[1,0]*L[2,0])
L[2,2] = np.sqrt(A[2,2] - L[2,0]**2 - L[2,1]**2)
L

array([[9, 0, 0],
       [-5, 5, 0],
       [5, 2, 3]])

In [64]:
L.T

array([[9, -5, 5],
       [0, 5, 2],
       [0, 0, 3]])

$$Ly=b\\
\begin{cases}
9y_{1} = 531\\
-5y_{1} + 5y_{2} = -460\\
5y_{1} + 2y_{2} +3y_{3} = 193
\end{cases}$$

In [65]:
y1 = 531/9
y2 = (5 * y1 - 460) / 5
y3 = (-5*y1 - 2*y2 + 193) / 3
y1, y2, y3

(59.0, -33.0, -12.0)

$$
L^{T}x = y\\
\begin{cases}
9x_{1}-5x_{2}+5x_{3} = 59\\
5x_{2} + 2x_{3} = -33\\
3x_{3} = -12
\end{cases}
$$

In [66]:
x3 = -12/3
x2 = (-33 - 2 * x3) / 5
x1 = (5*x2 - 5*x3 + 59)/ 9
x1, x2, x3

(6.0, -5.0, -4.0)

In [67]:
81*x1 - 45*x2 + 45*x3, (-45)*x1 + 50*x2 - 15*x3, 45*x1 - 15*x2 + 38*x3

(531.0, -460.0, 193.0)

<hr>

__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

In [75]:
A = np.array([[2, -1, 5],
              [1, 1, -3], 
              [2, 4, 1]])
B = np.array([[10], [-2], [1]])


In [73]:
def cramer_solver(A, B):
    """
    решение системы линейных уравнений методом Крамера
    """
    
    det = np.linalg.det(A)
    result = []
    if A.shape[0] == A.shape[1] and det != 0:
        for i in range(A.shape[0]):

            A_tmp = A.copy()
            A_tmp[:, i] = B[:, 0]

            result.append(np.linalg.det(A_tmp) / det)
        
    return result if len(result) > 0 else 'Нет решений для этого метода'

In [76]:
print(cramer_solver(A, B))

[2.0000000000000018, -1.0000000000000009, 1.0]
