In [1]:
import numpy as np

## Урок 2. ДЗ ##

### Часть 1 ###

1. Установить, какие произведения матриц  𝐴𝐵  и  𝐵𝐴  определены, и найти размерности полученных матриц:

а)  𝐴  — матрица  4×2 ,  𝐵  — матрица  4×2 ;

б)  𝐴  — матрица  2×5 ,  𝐵  — матрица  5×3 ;

в)  𝐴  — матрица  8×3 ,  𝐵  — матрица  3×8 ;

г)  𝐴  — квадратная матрица  4×4 ,  𝐵  — квадратная матрица  4×4 .

ОТВЕТ:

а) 
    AB - неопределено
    BA - неопределено
 
б)
    AB - 2х3
    BA - неопределено

в)
    AB - 8x8
    BA - 3x3
  
г)  в обоих случаях размерность 4x4
    

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$$
AB = \begin{pmatrix}
        1*4 + -2*0 & 1*-1 + -2*5 \\
        3*4 + 0*0 & 3*-1 + 0*5
\end{pmatrix} = 
\begin{pmatrix}
        4 & -11 \\
        12 & -3
\end{pmatrix}
$$
        

In [35]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
np.dot(A, B)

array([[  4, -11],
       [ 12,  -3]])

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$
3 * A = \begin{pmatrix}
3 & 21 \\ 
9 & -18
\end{pmatrix}$

$2 * B = \begin{pmatrix}
0 & 10 \\ 
4 & -2
\end{pmatrix}$

$2 * C = \begin{pmatrix}
8 & -16 \\ 
4 & 4
\end{pmatrix}$

$3A-2B+4C = \begin{pmatrix}
3-0+8 & 21-10-16 \\ 
9-4+4 & -18+2+4
\end{pmatrix}= \begin{pmatrix}
11 & -5 \\ 
9 & -12
\end{pmatrix}$

In [39]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
3*A - 2*B + 4*C

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$AA^{T}=\begin{pmatrix}
4*4 + 1*1 & 4*5 + 1*-2 & 4*2 + 1*3\\ 
5*4 + -2*1 & 5*5 + -2*-2 & 5*2 + -2*3\\ 
3*4 + 3*1 & 2*5 + 3*-2 & 2*2 + 3*3
\end{pmatrix}$

In [43]:
A = np.array([[4, 1], [5, -2], [2, 3]])
np.dot(A, A.T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [44]:
np.dot(A.T, A)

array([[45,  0],
       [ 0, 14]])

__5*__. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [152]:
def matrix_dot(A, B):
    "Функция умножения двух матриц"
    if len(A[0]) == len(B):
        result = []
        for a_row_num, row in enumerate(A):
            line = []
            for b_col_num in range(len(A)):
                tmp = 0
                for a_col_num, num in enumerate(row):
                    tmp += num * B[a_col_num][b_col_num]
                line.append(tmp)
            result.append(line)
    else:
        raise RuntimeError("Wrong matrix size")
    return result

In [156]:
A = [[1, -2], [3, 0], [3, 0]]
B = [[4, -1, 4], [0, 5, 6]] 

matrix_dot(A, B)

[[4, -11, -8], [12, -3, 12], [12, -3, 12]]


### Часть 2 ###

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} = sin^2x + cos^2x = 1$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix}=4*(5*9-0*1) - 0 + 0 = 180$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = 1\cdot(5\cdot9-6\cdot8) - 2\cdot(4\cdot9-6\cdot7) + 3\cdot(4\cdot8-5\cdot7) = 0$$

In [159]:
B = np.array([[4,2,3], [0,5,1], [0,0,9]])
np.linalg.det(B)

180.0

In [164]:
C = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(f'{np.linalg.det(C):0.5f}')

-0.00000


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2}) = det(A) * det(A) = 16$;
    
   б) $det(A^{T}) = 4$;
    
   в) $det(2A) = 2 * 4 = 8$.

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

In [167]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
np.linalg.det(A)

0.0

Ответ: матрица вырожденная, т.к. её определитель = 0

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

Ответ: 

3-я строка является суммой 1й и 2й => ее можно исключить
$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1
\end{pmatrix};$

3й столбец является суммой первого и второго => его тоже можно исключить. Останется матрица
$\begin{pmatrix}
1 & 2 \\ 
1 & 1
\end{pmatrix};$

Это означает, что ранг исходной матрицы = 2

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

Ответ:

третяя строка - сумма 1 и 2 => её исключаем
$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\  
2 & 3 & 5 & 6
\end{pmatrix}.$

первый и второй столбцы имеют линейную зависимость => следовательно один из них можно исключить

$\begin{pmatrix}
0  & 2 & 1\\ 
0  & 2 & 2\\  
2  & 5 & 6
\end{pmatrix}.$

Ранг исходной матрицы = 3

In [168]:
A = np.array([[1,2,3], [1,1,1], [2,3,4]])
np.linalg.matrix_rank(A)

2

In [169]:
B = np.array([[0,0,2,1], [0,0,2,2], [0,0,4,3], [2,3,5,6]])
np.linalg.matrix_rank(B)

3