### Урок 5. ДЗ ### 

1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$


In [22]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [23]:
A = np.array([[1, 2, 0],
              [0, 0, 5],
              [3, -4, 2],
              [1, 6, 5],
              [0, 1, 0]])
A

array([[ 1,  2,  0],
       [ 0,  0,  5],
       [ 3, -4,  2],
       [ 1,  6,  5],
       [ 0,  1,  0]])

In [24]:
U, s, W = np.linalg.svd(A)

V = W.T

D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [25]:
D

array([[8.82, 0.  , 0.  ],
       [0.  , 6.14, 0.  ],
       [0.  , 0.  , 2.53],
       [0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  ]])

In [26]:
U

array([[ 0.17,  0.16, -0.53, -0.8 , -0.16],
       [ 0.39, -0.53,  0.61, -0.43,  0.03],
       [-0.14, -0.82, -0.52,  0.14,  0.07],
       [ 0.89,  0.06, -0.25,  0.38, -0.06],
       [ 0.08,  0.11, -0.08, -0.11,  0.98]])

In [27]:
np.dot(U.T, U)

array([[ 1.,  0., -0., -0., -0.],
       [ 0.,  1.,  0., -0.,  0.],
       [-0.,  0.,  1., -0., -0.],
       [-0., -0., -0.,  1., -0.],
       [-0.,  0., -0., -0.,  1.]])

In [28]:
V

array([[ 0.07, -0.37, -0.93],
       [ 0.72,  0.67, -0.21],
       [ 0.69, -0.65,  0.31]])

In [29]:
np.dot(V.T, V)

array([[ 1.,  0.,  0.],
       [ 0.,  1., -0.],
       [ 0., -0.,  1.]])

In [30]:
#проверка
np.dot(np.dot(U, D), V.T)

array([[ 1.,  2.,  0.],
       [ 0., -0.,  5.],
       [ 3., -4.,  2.],
       [ 1.,  6.,  5.],
       [-0.,  1.,  0.]])

<hr>

2. Для матрицы из предыдущего задания найти:

    а) евклидову норму;
    
    б) норму Фробениуса.

In [37]:
# Евклидова норма
max(s), np.linalg.norm(A, ord=2)

(8.824868854820442, 8.824868854820444)

In [39]:
# норма Фробениуса

def frob_norm(A, s):
    """
    функция расчета нормы Фробениуса
    """
    result = 0
    for i in range(np.linalg.matrix_rank(A)):
        result += s[i]**2
    return np.sqrt(result)

np.linalg.norm(A, ord='fro'), frob_norm(A, s)

(11.045361017187261, 11.045361017187261)